import ConsultationCTA from '../ui/ConsultationCTA';
import {useState} from 'react';
import {cdValue} from '../../utils/planning';
const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD'});
export default function CDCalculator(){
 const [deposit,setDeposit]=useState('25000');
 const [offers,setOffers]=useState([{apy:'4',months:'6'},{apy:'4.25',months:'12'},{apy:'4.5',months:'24'}]);
 const valid=deposit.trim()!==''&&Number.isFinite(+deposit)&&+deposit>=0&&+deposit<=1e8&&offers.every(o=>o.apy.trim()!==''&&Number.isFinite(+o.apy)&&+o.apy>=0&&+o.apy<=20&&o.months.trim()!==''&&Number.isInteger(+o.months)&&+o.months>=1&&+o.months<=120);
 return <section className="planning-card" aria-labelledby="cd-title"><span>04 · COMPARE YOUR OPTIONS</span><h2 id="cd-title">CD comparison calculator</h2><p>Compare three fixed-rate certificates of deposit using the same deposit. Enter quoted APYs and terms. These examples are illustrative, not current bank offers.</p><label className="tool-field">Deposit per option ($)<input type="number" min="0" max="100000000" value={deposit} onChange={e=>setDeposit(e.target.value)}/></label>
 <div className="planning-inputs">{offers.map((o,i)=><fieldset className="cd-offer" key={i}><legend>CD {String.fromCharCode(65+i)}</legend>{(['apy','months'] as const).map(k=><label className="tool-field" key={k}>{k==='apy'?'APY (%)':'Term (months)'} — CD {String.fromCharCode(65+i)}<input type="number" min={k==='apy'?0:1} max={k==='apy'?20:120} step={k==='apy'?'0.01':'1'} value={o[k]} onChange={e=>setOffers(offers.map((v,j)=>j===i?{...v,[k]:e.target.value}:v))}/></label>)}</fieldset>)}</div>
 {!valid?<p role="alert">Enter a deposit from $0–$100 million, APYs from 0–20%, and whole-month terms from 1–120.</p>:<div className="planning-results" aria-live="polite">{offers.map((o,i)=>{const r=cdValue(+deposit,+o.apy,+o.months);return <div key={i}><small>CD {String.fromCharCode(65+i)} · {o.months} months · {o.apy}% APY</small><small>Estimated maturity value</small><strong>{money(r.balance)}</strong><small>Interest earned: {money(r.interest)}</small></div>;})}</div>}
 <p className="tool-note">Different terms have different maturity dates. More interest over a longer term does not necessarily mean a better annual yield. No renewal or future reinvestment rate is assumed.</p><details><summary>How this estimate works</summary><p className="tool-note">Maturity value = deposit × (1 + APY / 100) raised to (months / 12). APY already includes compounding; do not enter the nominal interest rate. Assumes a fixed APY, interest retained, and holding to maturity. Actual day counts and bank terms can change results. Excludes taxes, fees, early-withdrawal penalties, callable CDs, and market-linked CDs. Confirm withdrawal rules and deposit insurance with the institution. <a href="https://www.investor.gov/introduction-investing/investing-basics/investment-products/certificates-deposit-cds">Learn about CDs at Investor.gov.</a></p></details><ConsultationCTA label="Compare my savings options" /></section>;
}
