import {useState} from 'react';
import {Helmet} from 'react-helmet-async';
import {Link} from 'react-router-dom';
import {eligibility,mraMonths,pension,paycheck,retirementCategories,specialEligibility,specialPension} from '../utils/federal';
import ConsultationCTA from '../components/ui/ConsultationCTA';
import './PlanningTools.css';
const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const sources={rules:'https://www.opm.gov/retirement-center/fers-information/types-of-retirement/',formula:'https://www.opm.gov/retirement-center/fers-information/computation/'};
const checklist=['Request an official retirement estimate and verify creditable civilian service with agency HR.','Confirm military deposits, refunds, part-time service and any special retirement coverage.','For special-category jobs: verify covered-service dates, mandatory separation / exceptions, supplement eligibility and TSP access rules with HR; these are not calculated here.','Verify FEHB eligibility and coverage history; review PSHB rules if you are a postal employee.','Review FEGLI coverage and retirement reduction elections.','Review survivor elections with your spouse and confirm health coverage implications.','Update beneficiaries on TSP, life insurance and retirement benefits; review your trust.','Obtain Social Security estimates and evaluate your claiming date.','Plan for taxes, insurance, emergency reserves and the transition to retirement payments.','Discuss TSP withdrawal choices, investment risk and any FERS supplement eligibility with your benefits specialist.'];
export default function FederalPlanning(){
 const [f,setF]=useState({birth:'1966',age:'60',months:'0',years:'25',serviceMonths:'0',high3:'100000',survivor:'50'});
 const [category,setCategory]=useState('regular');
 const [covered,setCovered]=useState({years:'20',months:'0'});
 const special=category!=='regular'&&category!=='review';
 const [cash,setCash]=useState({tsp:'1500',social:'0',other:'0',taxes:'600',insurance:'400',expenses:'4500'});
 const [survive,setSurvive]=useState({own:'2000',social:'2000',other:'0',taxes:'400',insurance:'300',expenses:'4000',life:'250000'});
 const [checked,setChecked]=useState<string[]>([]);
 const valid=(o:Record<string,string>)=>Object.values(o).every(v=>v.trim()!==''&&Number.isFinite(+v)&&+v>=0&&+v<=100000000);
 const ok=valid(f)&&+f.birth>=1900&&+f.birth<=2026&&Number.isInteger(+f.birth)&&+f.age<=100&&+f.months<=11&&+f.serviceMonths<=11&&+f.years<=60&&['age','months','years','serviceMonths'].every(k=>Number.isInteger(+f[k as keyof typeof f]));
 const age=+f.age*12 + +f.months,service=+f.years*12 + +f.serviceMonths;
 const coveredMonths=+covered.years*12 + +covered.months;
 const coveredOk=valid(covered)&&Number.isInteger(+covered.years)&&Number.isInteger(+covered.months)&&+covered.months<=11&&coveredMonths<=service;
 const e=category==='review'?{eligible:false,reduction:0,label:'This retirement category requires an individual agency benefits review'}:special?specialEligibility(age,service,coveredMonths):eligibility(+f.birth,age,service);
 const p=special?specialPension(+f.high3,service,+f.survivor):pension(+f.high3,service,age,e.reduction,+f.survivor);
 const usable=ok&&(!special||coveredOk)&&e.eligible;
 const c=paycheck(p.monthly,+cash.tsp,+cash.social,+cash.other,+cash.taxes,+cash.insurance,+cash.expenses);
 const s=paycheck(p.survivor,+survive.own,+survive.social,+survive.other,+survive.taxes,+survive.insurance,+survive.expenses);
 function fields(o:Record<string,string>,labels:Record<string,string>,set:(v:Record<string,string>)=>void){return <div className="planning-inputs">{Object.entries(labels).map(([k,label])=><label className="tool-field" key={k}>{label}<input type="number" min="0" step={o===f?'1':'any'} max={100000000} value={o[k]} onChange={ev=>set({...o,[k]:ev.target.value})}/></label>)}</div>;}
 return <div className="planning-page"><Helmet><title>Federal Retirement Planning Center | Broussard Financial Services</title><meta name="description" content="Explore FERS eligibility, pension and survivor estimates, your retirement paycheck, and a federal employee retirement checklist."/><link rel="canonical" href="https://www.broussardfinancialservices.com/federal-planning"/></Helmet>
 <header className="planning-intro"><span>FOR FEDERAL EMPLOYEES</span><h1>Your next chapter.<br/><em>A clearer retirement picture.</em></h1><p>Connect your retirement date, pension and monthly budget. Free to use, with no signup. Your entries stay in this page and reset when you reload.</p><Link to="/federal-resources">Official federal employee resources →</Link></header>
 <nav className="tool-directory" aria-label="Federal planning sections">{[['eligibility','When can I retire?'],['paycheck','My retirement paycheck'],['survivor','Protect my household'],['checklist','My readiness checklist']].map(([id,title])=><a href={'#'+id} key={id}>{title} →</a>)}</nav>
 <p className="tool-note">Educational estimates for regular FERS and qualifying special-provisions FERS employees with at least five years of creditable civilian service. Agency-confirmed coverage is required; job title alone does not qualify you. CSRS, disability, deferred/postponed, part-time and mixed CSRS/FERS cases need individual review. No sick-leave credit, supplement, COLAs or deposit adjustments are included.</p>
 <section className="planning-card" id="eligibility"><span>01 · YOUR DATE & PENSION</span><h2>When could you retire?</h2><p>Enter your age and creditable service at the proposed separation date. This assumes your pension starts immediately. Exclude unused sick leave from service here.</p>
 <label className="tool-field">Retirement coverage<select value={category} onChange={ev=>setCategory(ev.target.value)}>{retirementCategories.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
 {special&&<><p className="tool-note">Use only agency-confirmed special retirement coverage. Enter total creditable service below, then the covered portion separately. Military deposits, unused sick leave and ordinary noncovered service do not establish the special-service threshold. Combining service categories requires HR confirmation.</p>{fields(covered,{years:'Special-covered service (whole years)',months:'Additional covered months (0–11)'},v=>setCovered(v as typeof covered))}{!coveredOk&&<p role="alert">Enter whole covered years and months (0–11), no greater than total creditable service.</p>}{category==='cbpo'&&<p className="tool-note">CBPO transitional / pre-July 6, 2008 service can require different treatment. This estimate models the standard 20/25-year covered-service case only; ask CBP HR to confirm coverage and computation before using it.</p>}</>}
 {category==='review'&&<p className="tool-note">Military reserve technicians and other special systems have separate conditions. We do not apply the law-enforcement / firefighter formula to these cases. Obtain an official estimate; our general income-gap and withdrawal tools can still help organize your budget.</p>}
 {fields(f,{birth:'Birth year',age:'Age at separation (whole years)',months:'Additional age months (0–11)',years:'Creditable service (whole years)',serviceMonths:'Additional service months (0–11)',high3:'Annual high-3 basic pay ($)'},v=>setF(v as typeof f))}
 <label className="tool-field">Spousal survivor election<select value={f.survivor} onChange={ev=>setF({...f,survivor:ev.target.value})}><option value="50">50% survivor benefit · 10% pension reduction</option><option value="25">25% survivor benefit · 5% pension reduction</option><option value="0">No survivor benefit · no survivor reduction</option></select></label>
 {!ok?<p role="alert">Enter complete nonnegative values. Use birth years 1900–2026, ages up to 100, service up to 60 years and whole months from 0–11.</p>:<><p><strong>{e.label}</strong></p>{category==='regular'?<p>Minimum retirement age: {Math.floor(mraMonths(+f.birth)/12)} years, {mraMonths(+f.birth)%12} months. Estimated age reduction: {(e.reduction*100).toFixed(2)}%.</p>:special&&<p>Special threshold: age 50 with 20 covered years, or any age with 25 covered years. For qualifying retirement, this estimate uses 1.7% of high-3 for the first 20 years plus 1% for additional creditable years, with no MRA age reduction. It does not switch to the regular 1.1% formula at age 62.</p>}{usable&&<div className="planning-results" aria-live="polite"><div><small>Monthly pension before survivor election</small><strong>{money(p.base)}</strong></div><div><small>Your monthly pension after election</small><strong>{money(p.monthly)}</strong></div><div><small>Monthly spousal survivor pension</small><strong>{money(p.survivor)}</strong></div></div>}</>}
 <p className="tool-note">Gross pension before taxes and insurance. High-3 means your highest consecutive three-year average basic pay. Lower survivor elections generally require spousal consent. Postponing an MRA + 10 pension may reduce its age penalty, but can affect the timing of benefits. Confirm elections and eligibility with HR.</p><p className="tool-note">Sources: <a href={sources.rules}>OPM retirement eligibility</a> · <a href={sources.formula}>OPM pension and survivor calculations</a>. Reviewed October 5, 2026.</p><ConsultationCTA label="Review my FERS retirement options"/></section>
 <section className="planning-card" id="paycheck"><span>02 · MONTHLY CASH FLOW</span><h2>Your federal retirement paycheck</h2><p>Your selected regular or special-provisions pension estimate above flows into this budget. Enter monthly gross income and your own estimated tax and insurance deductions. Include housing, food and other living costs in expenses, without counting taxes or insurance twice.</p>
 {fields(cash,{tsp:'TSP withdrawals ($/month)',social:'Social Security ($/month)',other:'Other income ($/month)',taxes:'Estimated total taxes ($/month)',insurance:'Insurance premiums ($/month)',expenses:'Living expenses ($/month)'},v=>setCash(v as typeof cash))}
 {usable&&valid(cash)?<div className="planning-results" aria-live="polite"><div><small>Gross monthly income</small><strong>{money(c.gross)}</strong></div><div><small>After tax & insurance estimates</small><strong>{money(c.net)}</strong></div><div><small>{c.remaining<0?'Monthly shortfall':'Monthly remaining'}</small><strong>{money(Math.abs(c.remaining))}</strong></div></div>:<p role="status">Complete valid inputs and an eligible immediate-retirement scenario above to see this budget.</p>}<p className="tool-note">Taxes are your input, not a computed tax liability. A monthly snapshot does not establish whether TSP withdrawals are sustainable. Benefits can start at different ages; update this budget for each stage.</p><Link to="/planning-tools#market">Stress-test these withdrawals against a market decline →</Link><ConsultationCTA label="Review my retirement paycheck"/></section>
 <section className="planning-card" id="survivor"><span>03 · HOUSEHOLD CONTINUITY</span><h2>If your spouse outlives you</h2><p>Compare your household budget above with an illustrative surviving-spouse budget. The survivor pension from your selected regular or special-provisions coverage flows in automatically. Enter your spouse’s own income and their expected total Social Security after your death—not both current checks added together.</p>
 {fields(survive,{own:'Spouse’s own pension / withdrawals ($/month)',social:'Expected survivor Social Security ($/month)',other:'Other continuing income ($/month)',taxes:'Survivor estimated taxes ($/month)',insurance:'Survivor insurance ($/month)',expenses:'Survivor living expenses ($/month)',life:'Life insurance death benefit ($)'},v=>setSurvive(v as typeof survive))}
 {usable&&valid(survive)?<div className="planning-results" aria-live="polite"><div><small>Survivor income after estimated deductions</small><strong>{money(s.net)}</strong></div><div><small>{s.remaining<0?'Survivor monthly shortfall':'Survivor monthly remaining'}</small><strong>{money(Math.abs(s.remaining))}</strong></div><div><small>Separate one-time life insurance benefit</small><strong>{money(+survive.life)}</strong></div></div>:<p role="status">Complete valid inputs and an eligible pension scenario above.</p>}<p className="tool-note">Life insurance is shown separately, not converted into guaranteed income. Confirm Social Security survivor eligibility and amounts with SSA. This scenario models the employee dying first; reverse roles with your adviser for a full household review. Survivor health coverage eligibility requires a separate benefits review.</p><ConsultationCTA label="Review our survivor income plan"/></section>
 <section className="planning-card" id="checklist"><span>04 · GET READY</span><h2>Your retirement readiness checklist</h2><p>{checked.length} of {checklist.length} items marked reviewed. Progress stays in this page only; print or save before leaving.</p><div className="readiness-list">{checklist.map(item=><label key={item}><input type="checkbox" checked={checked.includes(item)} onChange={ev=>setChecked(ev.target.checked?[...checked,item]:checked.filter(x=>x!==item))}/><span>{item}</span></label>)}</div><button className="tool-button" onClick={()=>window.print()}>Print / save my planning summary</button><p className="tool-note">Choose “Save as PDF” in your print dialog. Includes your inputs and current results. No account numbers or Social Security numbers are needed.</p><ConsultationCTA label="Review my results in a free consultation"/></section>
 </div>;
}
