import AnnuityBenefits from '../components/sections/AnnuityBenefits';
import EstateGuide from '../components/sections/EstateGuide';
import ServiceEducation from '../components/sections/ServiceEducation';
import {useEffect} from 'react';
import {useParams,Link} from 'react-router-dom';
import {Helmet} from 'react-helmet-async';
import ConsultationCTA from '../components/ui/ConsultationCTA';
import NotFound from './NotFound';
import './PlanningTools.css';
const pages:Record<string,{title:string;intro:string;help:string[];bring:string[]}>={
 'retirement-income':{title:'Retirement Income Planning',intro:'Connect your savings, pension, Social Security, and spending needs. Based in San Diego, our team helps clients understand how these pieces work together.',help:['Estimate the gap between expected spending and dependable income.','Explore how withdrawal timing and market losses could affect savings.','Discuss income priorities alongside taxes, liquidity, and family needs.'],bring:['An estimate of monthly retirement expenses.','A summary of pensions, Social Security estimates, and savings.','Your retirement timeline and questions.']},
 'federal-retirement':{title:'Federal Employee Retirement Planning',intro:'Our federal retirement consultants help you prepare with a clearer picture of your benefits. Discuss FERS, TSP, Social Security, and survivor-benefit decisions together.',help:['Organize benefit questions to resolve before retiring.','Discuss how pension income, Social Security, and TSP withdrawals fit together.','Review survivor-benefit priorities and questions for your agency benefits office.'],bring:['Your agency retirement estimate and planned retirement date.','A recent TSP statement and Social Security estimate.','Questions about survivor benefits and insurance coverage.']},
 'tsp-planning':{title:'TSP Planning & Education',intro:'Understand your Thrift Savings Plan in the context of your retirement. Explore contribution, withdrawal, and income-planning questions.',help:['Discuss your allocation and comfort with market fluctuations.','Review withdrawal questions alongside other income sources.','Compare considerations involved in keeping funds in TSP or moving them, including costs and features.'],bring:['Your current TSP statement for your own reference.','Your retirement timeline and expected income needs.','Questions about traditional and Roth balances or distributions.']},
 'trust-reviews':{title:'Estate Planning & Trust Services',intro:'Plan for the people and assets that matter to you. Our estate planning services include free trust and trust-account reviews, trust updates, and help setting up a new trust. Trust documents are prepared through a partner company.',help:['Review an existing trust and trust accounts free of charge.','Help with trust updates after changes in your family, property, or priorities.','Help with new trust setup and clarify your next steps.','Discuss your intended beneficiaries and how your estate planning goals fit with retirement, life insurance, and real estate.'],bring:['Your questions and a general overview of your goals.','Existing trust documents and a list of trust accounts for your own reference.','A summary of recent changes in your family or property.']},
 'annuities':{title:'Safe Retirement Income & Annuity Reviews',intro:'Plan for retirement income you can count on. We help you see whether an annuity could provide dependable payments for part of your monthly needs, and we review the annuity you already own. Your initial consultation and review are free.',help:['Review an existing annuity’s income options, fees, and surrender terms.','Discuss new annuity options in the context of your retirement income needs.','Understand access to your money and the conditions behind contract guarantees.'],bring:['Your current annuity statement and contract, if applicable.','An estimate of monthly expenses and other retirement income.','Questions about withdrawals, beneficiaries, and timing.']},
 'life-insurance':{title:'Life Insurance',intro:'Help the people who depend on you prepare for the unexpected. A free consultation starts with your family, financial responsibilities, and budget.',help:['Discuss the financial needs you want coverage to address.','Review current coverage and questions about your policy.','Explore coverage options that fit your priorities.'],bring:['A summary of any current life insurance coverage.','Your household’s main financial responsibilities.','Your questions and a comfortable premium budget.']},
 'real-estate':{title:'Real Estate: Buy, Sell & Invest',intro:'Our licensed Realtors help buyers, sellers, and real estate investors plan their next move. Tell us about your property goals in a free consultation.',help:['Discuss your plans for buying a home.','Prepare for a conversation about selling your property.','Explore your goals and questions about investment properties.'],bring:['The location and type of property you have in mind.','Your target timeline and general budget.','Questions about buying, selling, or investing.']}
};
const descriptions:Record<string,string>={
 'retirement-income':'Retirement income planning in San Diego. Connect savings, pensions, Social Security, and spending needs. Book a free consultation.',
 'federal-retirement':'Meet federal retirement consultants at Broussard Financial Services in San Diego. Discuss FERS, TSP, and survivor benefits in a free consultation.',
 'tsp-planning':'Understand TSP withdrawal, allocation, and retirement income questions with Broussard Financial Services. Schedule a free consultation.',
 'trust-reviews':'Free trust reviews in San Diego, trust updates, and new trust setup. Document preparation through our partner. Book a free estate planning consultation.',
 'annuities':'Explore safe retirement income and free annuity reviews in San Diego. Understand contract-defined payments, timing, and access to your savings.',
 'life-insurance':'Explore life insurance and review existing coverage with Broussard Financial Services in San Diego. Start with a free consultation.',
 'real-estate':'Buy, sell, or invest in real estate with our licensed Realtors. Discuss your property goals with Broussard Financial Services in San Diego.'
};
export default function ServicePage(){const {slug=''}=useParams();const page=pages[slug];useEffect(()=>{window.scrollTo(0,0)},[slug]);if(!page)return <NotFound/>;return <div className="planning-page"><Helmet><title>{`${page.title} | Broussard Financial Services`}</title><meta name="description" content={descriptions[slug]}/><link rel="canonical" href={`https://www.broussardfinancialservices.com/services/${slug}`}/></Helmet><header className="planning-intro"><Link to="/#services">← All services</Link><h1>{page.title}</h1><p>{page.intro}</p><ConsultationCTA label={slug==='annuities'?'Book my free annuity review':'Book my free consultation'}/></header>{slug==='annuities'&&<AnnuityBenefits/>}<section className="planning-card"><h2>How we can help</h2><ul>{page.help.map(t=><li key={t}>{t}</li>)}</ul></section><section className="planning-card"><h2>What to have handy</h2><ul>{page.bring.map(t=><li key={t}>{t}</li>)}</ul><p className="tool-note">You do not need to upload documents to book. Keep account numbers and sensitive documents out of the website contact form.</p></section>{slug==='trust-reviews'&&<EstateGuide/>}<ServiceEducation slug={slug}/><section className="planning-card"><h2>What happens in your consultation?</h2><p>Your booking is a free 30-minute phone call with one of our consultants. Share what you want to accomplish, ask questions, and discuss appropriate next steps. Mention your service interest when booking.</p><p>Trust reviews and initial consultations are complimentary. Any further services and applicable costs can be discussed before you decide how to proceed.</p><ConsultationCTA label="Choose a time to talk"/><p><Link to="/team">Meet the team →</Link></p></section></div>}
